version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
        - /usr/src/app/node_modules
    command: npm run start
    ports:
      - "9292:9292"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

